### ISSUE TITLE
This repository is amazing!

### ISSUE THREAD

**Issue by adamstirtan** [rojasjo/FullTextSearchDemo#11]
Hi @rojasjo, this is not an issue and please feel free to close it. I tried to find your contact information somewhere, but couldn't so resorted to opening an issue. I wanted to say thank you for creating this example code. I think you're an amazing engineer and this repository is very helpful for a project I'm working on. Wishing you the best! ❤️

**Comment by rojasjo** [comment]
@adamstirtan Thank you very much, I'm glad the code example helps. I'll add my contacts to my description.
