### ISSUE TITLE
Is there a sample data file ?

### ISSUE THREAD

**Issue by mediabuff** [rojasjo/FullTextSearchDemo#12]

**Comment by rojasjo** [comment]
Hi, there is an entire blog post series where you can find more about this repository:

- https://medium.com/@rojasjimenezjosea/lucene-net-powered-search-library-for-asp-net-core-ef8dc23959bd
- https://medium.com/@rojasjimenezjosea/c-search-library-powered-by-lucene-net-238026614107
- https://medium.com/@rojasjimenezjosea/lucene-net-facets-made-simple-1de9e2cdc314

The example file that i used for the movie can be found at: https://developer.imdb.com/non-commercial-datasets/

Cheers!

**Comment by mediabuff** [comment]
Great!. Thank you!
